wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684234167.279767
    t:
      1:
      - 1
      - 9
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 9
      - 11
      - 49
      - 51
      - 55
      3:
      - 23
      4: 3.10.6
      5: 0.15.2
      6: 4.29.0
      8:
      - 1
      - 5
